/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

/**
 *
 * @author Guilherme
 */
public class ElementoListaPanel extends javax.swing.JPanel {

    private String enunciado = "Enunciado";
    private int numopciones = 3;
    /**
     * Creates new form ElementoListaPanel
     */
    public ElementoListaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEnunciado = new javax.swing.JLabel();
        labelNumOpciones = new javax.swing.JLabel();

        labelEnunciado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEnunciado.setText("Enunciado");

        labelNumOpciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNumOpciones.setText("3 opciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(labelNumOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEnunciado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumOpciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelEnunciado;
    private javax.swing.JLabel labelNumOpciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the enunciado
     */
    public String getEnunciado() {
        return enunciado;
    }

    /**
     * @param enunciado the enunciado to set
     */
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
        labelEnunciado.setText(enunciado);
    }

    /**
     * @return the numopciones
     */
    public int getNumopciones() {
        return numopciones;
    }

    /**
     * @param numopciones the numopciones to set
     */
    public void setNumopciones(int numopciones) {
        this.numopciones = numopciones;
        labelNumOpciones.setText(numopciones + " opciones");
    }
}
