/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.model.Aficion;
import abd.p1.model.Pregunta;
import javax.swing.DefaultListModel;

/**
 *
 * @author Guilherme
 */
public class ListaAficionesPanel extends javax.swing.JPanel {
    DefaultListModel<Aficion> modelo = new DefaultListModel<>();
    /**
     * Creates new form ListaAficionesPanel
     */
    public ListaAficionesPanel() {
        initComponents();
        
        Aficion af1 = new Aficion();
        Aficion af2 = new Aficion();
        Aficion af3 = new Aficion();
        af1.setTexto("Futbol");
        af1.setId(1);
        af2.setTexto("Tenis");
        af2.setId(2);
        af3.setTexto("Asesinar");
        af3.setId(3);
        
        modelo.addElement(af1);
        modelo.addElement(af2);
        modelo.addElement(af3);
        jListAficiones.setModel(modelo);
        jListAficiones.setCellRenderer(new AficionCellRenderer());
    }
    
    public void addAficion(String aficion){
        Aficion af = new Aficion();
        Aficion af1 = new Aficion();
        af1 = modelo.lastElement();
        af.setTexto(aficion);
        af.setId(af1.getId()+ 1);
        modelo.addElement(af);
    }
    
    public void removeAficion(Aficion af){
        modelo.removeElement(af);
    }
    
    public Aficion getAficionSeleccionada(){
        return jListAficiones.getSelectedValue();
    }
    
    public void updateAficion(Integer id, String af){
        Aficion aficion = new Aficion();
        aficion.setTexto(af);
        modelo.setElementAt(aficion, id - 1);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAficiones = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jListAficiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Aficion> jListAficiones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
