/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import abd.p1.model.Usuario;
import javax.swing.DefaultListModel;

/**
 *
 * @author Guilherme
 */
public class ListaUsuariosPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListaUsuariosPanel
     */
    public ListaUsuariosPanel() {
        initComponents();
        Usuario usr1 = new Usuario();
        Usuario usr2 = new Usuario();
        Usuario usr3 = new Usuario();
        usr1.setNombre("Pepe");
        usr2.setNombre("Juan");
        usr3.setNombre("Mary");
        
        DefaultListModel<Usuario> modelo = new DefaultListModel<>();
        modelo.addElement(usr1);
        modelo.addElement(usr2);
        modelo.addElement(usr3);
        jListUsuarios.setModel(modelo);
        jListUsuarios.setCellRenderer(new UsuariosCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jListUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Usuario> jListUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
