/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

/**
 *
 * @author Guilherme
 */
public class OrientacionSexualPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrientacionSexualPanel
     */
    public OrientacionSexualPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSexo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelElegirSexo = new javax.swing.JLabel();
        labelBusca = new javax.swing.JLabel();
        buttonPreferencia = new javax.swing.JButton();
        labelPreferencia = new javax.swing.JLabel();

        labelSexo.setText("Sexo: ");

        jButton1.setText("Cambiar sexo");

        labelElegirSexo.setText("Elegir Sexo");

        labelBusca.setText("Busca: ");

        buttonPreferencia.setText("Cambiar preferencia");

        labelPreferencia.setText("Elegir Preferencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSexo)
                    .addComponent(labelBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreferencia)
                    .addComponent(labelElegirSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(jButton1)
                    .addComponent(labelElegirSexo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPreferencia)
                    .addComponent(labelBusca)
                    .addComponent(labelPreferencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPreferencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelElegirSexo;
    private javax.swing.JLabel labelPreferencia;
    private javax.swing.JLabel labelSexo;
    // End of variables declaration//GEN-END:variables
}
