/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abd.p1.view;

import javax.swing.JOptionPane;

public class OrientacionSexualPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form OrientacionSexualPanel
     */
    public OrientacionSexualPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSexo = new javax.swing.JLabel();
        buttonSexo = new javax.swing.JButton();
        labelElegirSexo = new javax.swing.JLabel();
        labelBusca = new javax.swing.JLabel();
        buttonPreferencia = new javax.swing.JButton();
        labelPreferencia = new javax.swing.JLabel();

        labelSexo.setText("Sexo: ");

        buttonSexo.setText("Cambiar sexo");
        buttonSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSexoActionPerformed(evt);
            }
        });

        labelElegirSexo.setText("Elegir Sexo");

        labelBusca.setText("Busca: ");

        buttonPreferencia.setText("Cambiar preferencia");
        buttonPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPreferenciaActionPerformed(evt);
            }
        });

        labelPreferencia.setText("Elegir Preferencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSexo)
                    .addComponent(labelBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPreferencia)
                    .addComponent(labelElegirSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSexo)
                    .addComponent(buttonSexo)
                    .addComponent(labelElegirSexo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPreferencia)
                    .addComponent(labelBusca)
                    .addComponent(labelPreferencia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSexoActionPerformed
            Object seleccion = JOptionPane.showInputDialog(
            null,
            "Seleccione una opcion",
            "Selector de opciones",
            JOptionPane.PLAIN_MESSAGE, //No muestra icono
            null,  
            new Object[] { "Masculino", "Femenino" }, 
            "Femenino");
            labelElegirSexo.setText(seleccion.toString());
    }//GEN-LAST:event_buttonSexoActionPerformed

    private void buttonPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPreferenciaActionPerformed
        Object seleccion = JOptionPane.showInputDialog(
            null,
            "Seleccione una opcion",
            "Selector de opciones",
            JOptionPane.PLAIN_MESSAGE, //No muestra icono
            null,  
            new Object[] { "Hombre", "Mujer" , "Ambos"}, 
            "Mujer");
            labelPreferencia.setText(seleccion.toString());
    }//GEN-LAST:event_buttonPreferenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPreferencia;
    private javax.swing.JButton buttonSexo;
    private javax.swing.JLabel labelBusca;
    private javax.swing.JLabel labelElegirSexo;
    private javax.swing.JLabel labelPreferencia;
    private javax.swing.JLabel labelSexo;
    // End of variables declaration//GEN-END:variables
}
