package abd.p1.view;

import java.util.List;

import abd.p1.model.Usuario;

public class PrincipalJFrame extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;

	private EditarPerfil ventanaPerfil;
	
	public EditarPerfil getVentanaPerfil() {
		return ventanaPerfil;
	}
	
	boolean isClosed = false;
    
    public boolean isClosed() {
		return isClosed;
	}
    
    public synchronized void close() {
    	setVisible(false);
    	isClosed = true;
    	notify();
    }
    
    public synchronized void waitUntilClose() {
    	while (!isClosed) {
    		try {
    			wait();
    		} catch (InterruptedException e) {
    			
    		}
    	}
    }

	/**
     * Creates new form Principal
     */
    public PrincipalJFrame() {
        ViewMgr.setMainWindow(this);
        initComponents();
        ventanaPerfil = new EditarPerfil(this, true);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
        	@Override
        	public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        		close();
        	}
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        listaUsuariosPanel = new abd.p1.view.ListaUsuariosPanel();
        listaPreguntasPanel = new abd.p1.view.ListaPreguntasPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.addTab("Usuarios", listaUsuariosPanel);
        jTabbedPane.addTab("Preguntas", listaPreguntasPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    private abd.p1.view.ListaPreguntasPanel listaPreguntasPanel;
    private abd.p1.view.ListaUsuariosPanel listaUsuariosPanel;
    // End of variables declaration//GEN-END:variables
    
    public void listUsers(List<Usuario> usrs) {
    	listaUsuariosPanel.setUsers(usrs);
    }

	public abd.p1.view.ListaUsuariosPanel getListaUsuariosPanel() {
		return listaUsuariosPanel;
	}
}
